CREATE TABLE EXTRATO_APP.TBMD_MOE  (
  CD_MOEDA NUMBER(5,0), 
  CD_MOEDA_BACEN NUMBER(3,0),   
  CD_MOEDA_ISO VARCHAR2(3 BYTE), 
  DS_MOEDA_PORT VARCHAR2(60 BYTE), 
  DS_MOEDA_INGLES VARCHAR2(60 BYTE), 
  DS_MOEDA_ALEMAO VARCHAR2(60 BYTE), 
    NM_MOEDA VARCHAR2(15 BYTE), 
    SM_MOEDA VARCHAR2(7 BYTE), 
    ID_SERIE_BDS NUMBER(10,0), 
    CD_SERIE_BDS VARCHAR2(100 BYTE), 
    DT_HORA DATE, 
    CD_USUARIO VARCHAR2(10 BYTE)
   ) ;