CREATE TABLE EXTRATO_APP.TCORP_PRODUTO
   (	CD_PRODUTO NUMBER(4,0), 
	CD_GRPROD NUMBER(3,0) NOT NULL, 
	DS_PRODUTO VARCHAR2(35 BYTE) NOT NULL, 
	DS_PRODUTO_PORT VARCHAR2(60 BYTE), 
	CD_USUARIO VARCHAR2(10 BYTE), 
	DT_HORA DATE, 
	CONSTRAINT "PRODUTO_PK" PRIMARY KEY ("CD_PRODUTO"));
