  CREATE TABLE EXTRATO_APP.CLIENT_EXTRACT_MANAGEMENT 
   (CD_CLI_BR NUMBER(8,0), 
	NM_CLI VARCHAR2(60 BYTE), 
	VR_AGENDAMENTO VARCHAR2(10 BYTE), 
	VR_PERIODO VARCHAR2(60 BYTE), 
	VR_HORARIO VARCHAR2(60 BYTE), 
	VR_DIA_SEMANA VARCHAR2(60 BYTE), 
	DT_REF VARCHAR2(10 BYTE), 
	VR_TIPO_RELATORIO VARCHAR2(10 BYTE), 
	VR_EMAIL_FLAG VARCHAR2(5 BYTE),
	CONSTRAINT "PK_CP" PRIMARY KEY ("CD_CLI_BR", "VR_PERIODO"));