insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (18, 'LIBOR', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (96, 'LIBOR FIXED', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (97, 'IDI2003', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (99, 'NDF020407', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (101, 'IGPM IND PLENP', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (150, 'NDF011007_2', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (152, 'NDF011007_3', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (201, 'IPCA', 'PRE', 0, 0, null, 'MEFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (208, 'CSN_USD_2', 'PRE', 220, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (210, 'CSN_USD_4', 'PRE', 220, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (212, 'CSN_JPY_2', 'PRE', 470, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (214, 'CSN_JPY_4', 'PRE', 470, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (218, 'FEC. NOVA LIRA TURCA', 'PRE', 642, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (258, 'SUGAR_0711', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (273, 'STEEL', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (294, 'Libor 9M', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (291, 'COTA FIDIC DB 1', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (303, 'Coroa Sueca', 'PRE', 70, 790, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (301, 'UFPA', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (252, 'BASQUET', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (267, 'ZINC', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (269, 'FEC. DOLAR AUSTRALIANO', 'PRE', 150, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (276, 'OURO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (278, 'Platina', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (288, 'BASKET_2', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (290, 'GOLD', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (217, 'NOVA LIRA TURCA', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (224, 'PTAX ASIATICA', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (234, 'COBREOUT10', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (236, 'ALU_110302_1982', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (238, 'ALU_110504_1992', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (240, 'ALU_110705_2010', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (242, 'ALU_110902_2010', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (244, 'ALU_111103_2025', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (246, 'COP_110104_6133', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (248, 'COP_110302_6133', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (250, 'ZAR_100104_780', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (259, 'KRW', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (263, 'ALUMINIO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (265, 'PESO MEXICANO', 'PRE', 741, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (274, 'PALADIO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (281, 'Dólar Neozelandês', 'PRE', 245, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (283, 'COTTON', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (221, 'Dólar de Fechamento', 'PRE', 220, 790, 'S', 'MEFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (225, 'PTAX ASIATICA_II', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (229, 'APTX_20100531_1', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (231, 'PT_20100730_191', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (261, 'SUGAR_OCT11', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (285, 'Libor 3M', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (223, 'Libor 6M', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (227, 'DBOUROLON', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (255, 'SUGAR_12318', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (257, 'SUGAR_12320', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (280, 'WTI', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (1, 'DOLAR SPOT', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (3, 'IGPDI', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (5, 'Libor 1 Month', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (7, 'Libor 11 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (9, 'Libor 2 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (11, 'Libor 4 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (13, 'Libor 6 Month', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (15, 'Libor 8 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (17, 'LIBOR INTERNO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (22, 'PRE-SELIC', 'MIS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (24, 'PTAX FLUT', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (26, 'SELIC', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (28, 'TR', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (31, 'EURO', 'PRE', 978, 790, 'N', null, 'N', null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (33, 'DEB-IBAN11', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (35, 'DEB-IVSC11 B', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (37, 'COTAS FDS', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (39, 'DEB.ARMCO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (41, 'DEB.EB COSM.', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (43, 'DEB.INTEL', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (45, 'DEB.METALCICLO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (47, 'DEB.TELESISA', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (49, 'LIBRA ESTERLINA', 'PRE', 540, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (51, 'IENE', 'PRE', 470, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (53, 'FRANCO FRANCES', 'PRE', 395, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (55, 'COROA SUECA', 'PRE', 70, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (57, 'PTAX+LIBOR', 'PRE', 0, 0, 'N', 'TRFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (59, 'Libor Iene - 1 Week', 'PRE', 470, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (61, 'COROA DINAMARQUESA', 'PRE', 55, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (63, 'FEC. COROA NORUEGUESA', 'PRE', 65, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (65, 'FEC. DOLAR CANADENSE', 'PRE', 165, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (67, 'FEC. EURO', 'PRE', 978, 220, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (69, 'FEC. FRANCO BELGA', 'PRE', 360, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (71, 'FEC. FRANCO SUIÇO', 'PRE', 425, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (73, 'FEC. LIRA ITALIANA', 'PRE', 595, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (75, 'FEC. PESETA ESPANHOLA', 'PRE', 700, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (77, 'IBOVESPA', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (79, 'BESP4', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (81, 'Libor Crossborder', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (83, 'Libor Yen - 1 Month', 'PRE', 470, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (85, 'Libor Yen - 6 Month', 'PRE', 470, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (87, 'Libor Euro - 1 Month', 'PRE', 978, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (89, 'Libor Euro - 6 Month', 'PRE', 978, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (91, 'Swap Pre Int 1Y', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (93, 'PTAX+LIBOR 6M+1,75%', 'PRE', 0, 0, 'N', 'SEFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (95, 'RANGE OF PTAX', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (328, 'FEC. YUAN CHINES', 'PRE', 795, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (330, 'FEC. PESO ARGENTINO', 'PRE', 706, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (351, 'PRE_EXP360', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (353, 'EURO 30_360', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (391, 'UFRS', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (-1, 'NÃO IDENTIFICADO', '-', null, null, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (0, 'NÃO INFORMADO', '-', null, null, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (999, 'Não se Aplica', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (19, 'USD FIXED', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (106, 'PESO URUGUAIO', 'PRE', 0, 0, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (98, 'COTA FIF GM', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (100, 'NDF020407_2', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (199, 'NDF011007', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (151, 'NDF020108', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (200, 'NDF010408', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (207, 'CSN_USD_1', 'PRE', 220, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (209, 'CSN_USD_3', 'PRE', 220, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (211, 'CSN_JPY_1', 'PRE', 470, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (213, 'CSN_JPY_3', 'PRE', 470, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (215, 'NDF03012011', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (220, 'Bovespa', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (272, 'NICKEL', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (293, 'Libor 4M', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (302, 'PMAM3_TRS', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (292, 'COTA FIDIC DB 2', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (300, 'UFRJ', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (304, 'DB TRADE S INDE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (253, 'PTAX-PHOENIX', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (268, 'SILVER', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (270, 'FEC. PESO MEXICANO', 'PRE', 741, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (277, 'COFFEE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (279, 'COFFEE_KCN1', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (289, 'BASKET_8', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (216, 'IPCA-E', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (219, 'SOJA_LIMIT1', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (233, 'COBRESET10', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (235, 'COBREDEZ10', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (237, 'ALU_110404_1992', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (239, 'ALU_110602_1992', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (241, 'ALU_110802_2010', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (243, 'ALU_111004_2025', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (245, 'ALU_111202_2025', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (247, 'COP_110202_6133', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (249, 'ALU_110202_1982', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (251, 'ZAR_100104_820', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (262, 'SUGAR', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (264, 'COBRE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (266, 'DOLAR AUSTRALIANO', 'PRE', 150, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (275, 'ESTANHO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (282, 'Rande - África do Sul', 'PRE', 785, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (287, 'SOJA', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (222, 'Euro de Fechamento', 'PRE', 978, 220, 'S', 'MEFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (228, 'EURO PESO MEXICANO', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (230, 'APTX_20100630_1', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (232, 'PT_20100830_192', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (271, 'FEC. DOLAR NEOZELANDES', 'PRE', 245, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (286, 'COFFEE_KCU2', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (226, 'DBCOMMIN', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (254, 'SUGAR_12317', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (256, 'SUGAR_12319', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (260, 'SOJA_MAI11', 'POS', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (284, 'RICE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (2, 'CDI CETIP', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (4, 'IGPM - Taxa mes', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (6, 'Libor 10 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (8, 'Libor 12 Month', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (10, 'Libor 3 Month', 'PRE', 220, 790, 'N', 'TRFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (12, 'Libor 5 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (14, 'Libor 7 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (16, 'Libor 9 Month', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (21, 'PRE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (23, 'PTAX', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (30, 'TJLP', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (27, 'TBF', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (29, 'UFIR', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (32, 'DEB-BESC13', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (34, 'DEB-IVSC11 A', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (36, 'DEB-IVSC11 C', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (38, 'Libor 1 Week', 'PRE', 220, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (40, 'DEB.CBE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (42, 'DEB.FANAPE', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (44, 'DEB.LATINA', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (46, 'DEB.STACO', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (48, 'MARCO ALEMAO', 'PRE', 610, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (50, 'LIRA ITALIANA', 'PRE', 595, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (52, 'FRANCO SUICO', 'PRE', 425, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (54, 'DOLAR CANADENSE', 'PRE', 165, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (56, 'COROA NORUEGUESA', 'PRE', 65, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (58, 'DEBENTURES', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (60, 'Libor Euro - 1 Week', 'PRE', 978, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (62, 'FEC. COROA DINAMARQUESA', 'PRE', 55, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (64, 'FEC. COROA SUECA', 'PRE', 70, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (66, 'FEC. ESCUDO PORTUGUES', 'PRE', 295, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (68, 'FEC. FLORIM HOLANDES', 'PRE', 335, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (70, 'FEC. FRANCO FRANCES', 'PRE', 395, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (72, 'FEC. LIBRA ESTERLINA', 'PRE', 540, 220, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (74, 'FEC. MARCO ALEMAO', 'PRE', 610, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (76, 'FEC. YEN JAPONES', 'PRE', 470, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (78, 'URTJLP', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (80, 'IDI2000', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (82, 'ESCUDO PORTUGUES', 'PRE', 315, 790, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (84, 'Libor Yen - 3 Month', 'PRE', 470, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (86, 'Libor Yen - 12 Month', 'PRE', 470, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (88, 'Libor Euro - 3 Month', 'PRE', 978, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (90, 'Libor Euro - 12 Month', 'PRE', 978, 790, 'N', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (92, 'PTAX+LIBOR 6M+3,25%', 'PRE', 0, 0, 'N', 'SEFI', null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (94, 'BRAZIL GLOBAL 24', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (305, 'IFRS G A', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (329, 'FEC. RAND SUL-AFRICANO', 'PRE', 785, 220, 'S', null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (332, 'INPC', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (352, 'PRE 30_360', 'PRE', 0, 0, null, null, null, null);

insert into EXTRATO_APP.tbdw_dim_inx (CD_INDEXADOR, NM_INDEXADOR, FL_TIPO_INX, CD_MOEDA_DE, CD_MOEDA_PARA, FL_TIPO_PARIDADE, CD_TPPE, FL_TIPO_PARIDADE_MTM, CD_INX_CERI)
values (371, 'PTAX 30_360', 'PRE', 0, 0, null, null, null, null);

commit;

