insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (1, 'DBI', 'DBI');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (2, 'IRON', 'IRON');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (3, 'SBRF', 'SBS - RENDA FIXA');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (4, 'SBSW', 'SBS - SWAP');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (5, 'SGR', 'SGR COBRANÇA');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (6, 'SGRR', 'SGR RECEBÍVEIS');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (7, 'SNRV', 'SIAN - RENDA VARIAVEL');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (8, 'SYEP', 'FUNÇÃO');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (41, 'SHCC', 'CHIPSHOP - CONTA CORRENTE EXTERIOR');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (42, 'SHCS', 'CHIPSHOP - CAMBIO SINTETICA');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (61, 'SGRE', 'SGR Empréstimos e Fianças');

insert into EXTRATO_APP.TBDW_DIM_SIS (CD_SEQ_SIS_ORIG, CD_SIS_ORIG, NM_SISTEMA) values (21, 'SHCB', 'CHIPSHOP');

commit;
