insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (8, 'ETB', 'BIRR           ', 'A', to_date('28-07-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (10, 'ARG', 'AUSTRAL        ', 'A', to_date('16-12-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (20, 'PAB', 'BALBOA/PANAMA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (26, 'VEF', 'BOLIVAR VEN', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (35, 'GHS', 'CEDI GANA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (45, 'SVC', 'COLON/EL SALVAD', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (51, 'NIO', 'CORDOBA OURO   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (57, 'EEK', 'COROA ESTONIA', 'A', to_date('17-01-2011', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (60, 'ISK', 'COROA ISLND/ISL', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (70, 'SEK', 'COROA SUECA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (78, 'NCZ', 'CRUZADO NOVO   ', 'A', to_date('15-03-1990', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (80, 'CR$', 'CRUZEIRO       ', 'A', to_date('27-02-1986', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (85, 'CR$', 'CRUZEIRO REAL  ', 'A', to_date('30-06-1994', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (90, 'GMD', 'DALASI/GAMBIA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (100, 'KWD', 'DINAR/KWAIT    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (110, 'YD', 'DINAR IEMENITA ', 'B', to_date('31-07-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (120, 'DIN', 'DINAR IUGOSLAVO', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (130, 'LYD', 'DINAR/LIBIA    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (133, 'RSD', 'DINAR SERVIO SE', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (135, 'TND', 'DINAR/TUNISIA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (138, 'SDR', 'DIREITO ESPECIA', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (145, 'AED', 'DIRHAM/EMIR.ARA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (150, 'AUD', 'DOLAR AUSTRALIA', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (160, 'BMD', 'DOLAR/BERMUDAS ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (170, 'GYD', 'DOLAR DA GUIANA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (175, 'BBD', 'DOLAR/BARBADOS ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (185, 'BND', 'DOLAR BRUNEI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (195, 'SGD', 'DOLAR CINGAPURA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (200, 'FJD', 'DOLAR FIJI', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (210, 'TTD', 'DOLAR/TRIN. TOB', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (217, 'ZWL', 'DOLAR ZIMBABUE', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (225, 'ETB', 'DOLAR/ETIOPIA  ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (235, 'LRD', 'DOLAR LIBERIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (245, 'NZD', 'DOLAR/NOVA ZELA', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (255, 'SRD', 'DOLAR/SURINAME ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (270, 'GRD', 'DRACMA/GRECIA  ', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (295, 'CVE', 'ESCUDO CABO VER', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (320, 'TPE', 'ESCUDO TIMOR LE', 'A', to_date('01-01-2000', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (328, 'AWG', 'FLORIM/ARUBA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (333, 'SRD', 'DOLAR/SURINAME ', 'A', to_date('06-09-2005', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (345, 'HUF', 'FORINT/HUNGRIA ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (361, 'FBF', 'FRANCO BELGA FI', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (365, 'BIF', 'FRANCO/BURUNDI ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (370, 'XAF', 'FRANCO CFA BEAC', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (380, 'XPF', 'FRANCO CFP', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (390, 'DJF', 'FRANCO/DJIBUTI ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (398, 'GNF', 'FRANCO/GUINE   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (405, 'MGF', 'FRANCO MALGAXE ', 'A', to_date('14-06-2010', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (410, 'MF', 'FRANCO MALI    ', 'A', to_date('31-07-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (425, 'CHF', 'FRANCO SUICO   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (450, 'PYG', 'GUARANI/PARAGUA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (470, 'JPY', 'IENE           ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (482, 'GEL', 'LARI GEORGIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (490, 'ALL', 'LEK ALBANIA REP', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (500, 'SLL', 'LEONE/SERRA LEO', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (505, 'ROL', 'LEU/ROMENIA    ', 'A', to_date('17-12-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (510, 'BGN', 'LEV/BULGARIA, R', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (530, 'GIP', 'LIBRA/GIBRALTAR', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (540, 'GBP', 'LIBRA ESTERLINA', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (550, 'IEP', 'LIBRA/IRLANDA  ', 'B', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (560, 'LBP', 'LIBRA/LIBANO   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (570, 'SHP', 'LIBRA/STA HELEN', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (580, 'LSD', 'LIBRA SUDANESA ', 'B', to_date('21-05-1996', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (595, 'ITL', 'LIRA ITALIANA  ', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (601, 'LTL', 'LITA LITUANIA', 'A', to_date('31-12-2014', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (605, 'M', 'MARCO          ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (608, 'TMT', 'NOVO MANAT TURC', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (612, 'BAM', 'MARCO CONV BOSN', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (620, 'MZM', 'METICAL MOCAMBI', 'A', to_date('01-07-2006', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (625, 'ERN', 'NAKFA ERITREIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (635, 'AOA', 'KWANZA/ANGOLA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (640, 'TWD', 'NOVO DOLAR/TAIW', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (645, 'MXN', 'NOVO PESO/MEXIC', 'A', to_date('08-07-2008', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (650, 'N$', 'NOVO PESO URUGU', 'A', to_date('03-06-2008', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (660, 'PEN', 'NOVO SOL/PERU  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (665, 'BTN', 'NGULTRUM/BUTAO ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (680, 'TOP', 'PAANGA/TONGA   ', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (690, 'ADP', 'PESETA/ANDORA  ', 'A', to_date('27-02-2004', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (705, '$(A', 'PESO ARGENTINO ', 'A', to_date('03-11-1986', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (710, '$B', 'PESO BOLIVIANO ', 'A', to_date('20-09-1993', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (720, 'COP', 'PESO/COLOMBIA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (730, 'DOP', 'PESO/REP. DOMIN', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (738, 'GWP', 'PESO/GUINE BISS', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (741, 'MXN', 'PESO/MEXICO    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (755, 'BWP', 'PULA/BOTSWANA  ', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (765, 'ZMK', 'QUACHA ZAMBIA', 'A', to_date('31-12-2012', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (770, 'GTQ', 'QUETZAL/GUATEMA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (776, 'UAK', 'KARBOVANETS    ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (779, 'HRK', 'KUNA/CROACIA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (785, 'ZAR', 'RANDE/AFRICA SU', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (795, 'CNY', 'RENMIMBI IUAN', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (800, 'QAR', 'RIAL/CATAR     ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (810, 'YER', 'RIAL/IEMEN     ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (820, 'SAR', 'RIAL/ARAB SAUDI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (828, 'MYR', 'RINGGIT/MALASIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (830, 'RUB', 'RUBLO/RUSSIA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (840, 'MUR', 'RUPIA/MAURICIO ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (850, 'SCR', 'RUPIA/SEYCHELES', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (860, 'INR', 'RUPIA/INDIA    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (870, 'MVR', 'RUFIA/MALDIVAS ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (880, 'ILS', 'SHEKEL/ISRAEL  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (892, 'KGS', 'SOM QUIRGUISTAO', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (895, 'ECS', 'SUCRE EQUADOR', 'A', to_date('09-09-2000', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (910, 'WS$', 'TALA           ', 'B', to_date('27-07-1988', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (912, 'WST', 'TALA SAMOA', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (914, 'SIT', 'TOLAR/ESLOVENIA', 'A', to_date('03-03-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (916, 'CLF', 'UNID FOMENTO CH', 'A', to_date('20-01-2014', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (920, 'VUV', 'VATU VANUATU', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (930, 'KRW', 'WON COREIA SUL', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (945, 'T S', 'XELIM DA TANZAN', 'A', to_date('25-11-1999', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (950, 'KES', 'XELIM/QUENIA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (960, 'SOS', 'XELIM/SOMALIA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (971, 'ZRN', 'NOVO ZAIRE/ZAIR', 'A', to_date('30-10-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (978, 'EUR', 'EURO', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (982, 'CL$', 'DOLAR-BULGARIA ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (984, 'CL$', 'DOLAR-HUNGRIA  ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (988, 'CL$', 'DOLAR-IUGOSLAVI', null, to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (991, 'XAG', 'PRATA-DEAFI    ', 'B', to_date('10-06-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (993, 'XPD', 'PALADIO        ', 'B', to_date('10-06-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (995, 'BUA', 'BUA            ', 'B', to_date('17-12-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (998, 'XAU', 'DOLAR OURO     ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (-1, null, 'NÃO IDENTIF.', null, null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (0, null, 'NÃO INFORMADO', null, null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (5, 'AFN', 'AFEGANE AFEGANI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (9, 'ETB', 'BIRR/ETIOPIA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (15, 'THB', 'BATH/TAILANDIA ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (25, 'VEB', 'BOLIVAR/VENZUEL', 'A', to_date('17-12-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (30, 'BOB', 'BOLIVIANO/BOLIV', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (40, 'CRC', 'COLON/COSTA RIC', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (50, 'NIC', 'CORDOBA/NICARAG', 'A', to_date('31-07-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (55, 'DKK', 'COROA DINAMARQU', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (58, 'SKK', 'COROA ESLOVACA ', 'A', to_date('03-03-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (65, 'NOK', 'COROA NORUEGUES', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (75, 'CZK', 'COROA TCHECA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (79, 'CZ$', 'CRUZADO        ', 'A', to_date('15-01-1989', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (83, 'CR$', 'CRUZEIRO       ', 'A', to_date('31-07-1993', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (88, 'RUR', 'CUPON GEORGIANO', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (95, 'DZD', 'DINAR ARGELINO ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (105, 'BHD', 'DINAR/BAHREIN  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (115, 'IQD', 'DINAR/IRAQUE   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (125, 'JOD', 'DINAR/JORDANIA ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (132, 'MKD', 'DINAR/MACEDONIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (134, 'SDG', 'NOVA LIBRA SUDA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (136, 'SSP', 'LIBRA SUL SUDAN', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (139, 'MAD', 'DIRHAM/MARROCOS', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (148, 'STD', 'DOBRA S TOME PR', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (155, 'BSD', 'DOLAR/BAHAMAS  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (165, 'CAD', 'DOLAR CANADENSE', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (173, 'NAD', 'DOLAR DA NAMIBI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (180, 'BZD', 'DOLAR/BELIZE   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (190, 'KYD', 'DOLAR CAYMAN', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (197, 'CLF', 'UNIDADE DE FOME', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (205, 'HKD', 'DOLAR HONG KONG', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (215, 'XCD', 'DOLAR CARIBE OR', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (220, 'USD', 'DOLAR DOS EUA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (230, 'JMD', 'DOLAR/JAMAICA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (240, 'M$', 'DOLAR MALAIO   ', 'A', to_date('24-04-1986', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (250, 'SBD', 'DOLAR IL SALOMA', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (260, 'VND', 'DONGUE/VIETNAN ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (275, 'AMD', 'DRAM ARMENIA RE', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (315, 'PTE', 'ESCUDO PORTUGUE', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (325, 'ANG', 'GUILDER ANTILHA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (330, 'SRG', 'FLORIM/SURINAME', 'A', to_date('06-09-2005', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (335, 'NLG', 'FLORIM HOLANDES', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (360, 'BEF', 'FRANCO BELGA/BE', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (363, 'CDF', 'FRANCO CONGOLES', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (368, 'KMF', 'FRANCO/COMORES ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (372, 'XOF', 'FRANCO CFA BCEA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (385, 'BIF', 'FRANCO/BURUNDI ', 'A', to_date('31-07-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (395, 'FRF', 'FRANCO FRANCES ', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (400, 'LUF', 'FRANCO LUXEMBUR', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (406, 'MGA', 'ARIARY MADAGASC', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (420, 'RWF', 'FRANCO/RUANDA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (440, 'HTG', 'GOURDE/HAITI   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (460, 'UAH', 'HRYVNIA UCRANIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (480, 'I', 'INTI PERUANO   ', 'A', to_date('01-02-1991', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (485, 'LVL', 'LAT LETONIA REP', 'A', to_date('31-12-2013', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (495, 'HNL', 'LEMPIRA/HONDURA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (503, 'MDL', 'LEU/MOLDAVIA, R', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (506, 'RON', 'NOVO LEU/ROMENI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (520, 'CYP', 'LIBRA CIP/CHIPR', 'A', to_date('03-03-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (535, 'EGP', 'LIBRA/EGITO    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (545, 'FKP', 'LIBRA/FALKLAND ', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (555, 'IL', 'LIBRA ISRAELENS', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (565, 'MTL', 'LIRA/MALTA     ', 'B', to_date('03-03-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (575, 'SYP', 'LIBRA/SIRIA, RE', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (585, 'SZL', 'LILANGENI/SUAZI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (600, 'TRL', 'LIRA TURQUIA', 'A', to_date('17-12-2009', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (603, 'LSL', 'LOTI/LESOTO    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (607, 'AZN', 'MANAT ARZEBAIJA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (610, 'DEM', 'MARCO ALEMAO   ', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (615, 'FIM', 'MARCO FINLANDES', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (622, 'MZN', 'NOVA METICAL/MO', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (630, 'NGN', 'NAIRA/NIGERIA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (637, 'YUM', 'NOVO DINAR IUGO', 'A', to_date('27-02-2004', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (642, 'TRY', 'LIRA TURCA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (646, 'MXN', 'NOVO PESO/MEXIC', 'A', to_date('03-06-2008', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (651, 'N$', 'NOVO PESO URUGU', 'A', to_date('03-06-2008', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (663, 'ZRN', 'NOVO ZAIRE/ZAIR', 'A', to_date('30-10-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (670, 'MRO', 'UGUIA MAURITANI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (685, 'MOP', 'PATACA/MACAU   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (700, 'ESP', 'PESETA ESPANHOL', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (706, 'ARS', 'PESO ARGENTINO', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (715, 'CLP', 'PESO CHILE', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (725, 'CUP', 'PESO/CUBA      ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (735, 'PHP', 'PESO/FILIPINAS ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (740, 'MEX', 'PESO MEXICANO  ', 'A', to_date('31-05-1993', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (745, 'UYU', 'PESO/URUGUAIO  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (760, 'MWK', 'QUACHA/MALAVI  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (766, 'ZMW', 'QUACHA ZAMBIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (775, 'MMK', 'QUIATE/BIRMANIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (778, 'PGK', 'KINA/PAPUA N GU', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (780, 'LAK', 'QUIPE/LAOS, REP', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (790, 'BRL', 'REAL BRASIL', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (796, 'CNH', 'RENMINBI HONG K', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (805, 'OMR', 'RIAL/OMA       ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (815, 'IRR', 'RIAL/IRAN, REP ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (825, 'KHR', 'RIEL/CAMBOJA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (829, 'BYR', 'RUBLO BELARUS', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (835, 'TJS', 'SOMONI TADJIQUI', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (845, 'NPR', 'RUPIA/NEPAL    ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (855, 'LKR', 'RUPIA/SRI LANKA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (865, 'IDR', 'RUPIA/INDONESIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (875, 'PKR', 'RUPIA/PAQUISTAO', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (890, 'S/.', 'SOL PERUANO    ', 'A', to_date('26-04-1988', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (893, 'UZS', 'SOM UZBEQUISTAO', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (905, 'BDT', 'TACA/BANGLADESH', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (911, 'WST', 'TALA SAMOA OC', 'A', to_date('02-12-2014', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (913, 'KZT', 'TENGE CAZAQUIST', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (915, 'MNT', 'TUGRIK/MONGOLIA', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (918, 'XEU', 'UNID.MONET.EURO', 'B', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (925, 'KPW', 'WON/COREIA NORT', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (940, 'ATS', 'XELIM AUSTRIACO', 'A', to_date('02-01-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (946, 'TZS', 'XELIM/TANZANIA ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (955, 'UGX', 'XELIM/UGANDA   ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (970, 'ZRN', 'NOVO ZAIRE  ZAI', 'A', to_date('31-07-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (975, 'PLN', 'ZLOTY/POLONIA  ', 'A', null);

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (980, 'CL$', 'DOLAR-EX-ALEM.O', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (983, 'CL$', 'DOLAR-GRECIA   ', null, to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (986, 'CL$', 'DOLAR-ISRAEL   ', null, to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (990, 'CL$', 'DOLAR-POLONIA  ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (992, 'CL$', 'DOLAR-ROMENIA  ', 'A', to_date('04-08-1998', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (994, 'PLA', 'PLATINA        ', 'B', to_date('10-06-2002', 'dd-mm-yyyy'));

insert into FDWB.TBDW_DIM_MOE (CD_MOEDA, CD_MOEDA_ISO, NM_MOEDA, TP_PARIDADE_DOLAR, DT_EXCLUSAO_PTAX)
values (996, 'FUA', 'FUA            ', 'B', to_date('17-12-2009', 'dd-mm-yyyy'));

commit;
